# Generated by Django 2.0 on 2018-06-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resorce',
            name='name',
            field=models.CharField(max_length=30, verbose_name='课程名'),
        ),
        migrations.AlterField(
            model_name='resorce',
            name='url',
            field=models.TextField(verbose_name='url'),
        ),
    ]
